branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: soundgood-backend
  branch: null
  default_ec2_keyname: new
  default_platform: Python 3.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
